// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLri7BzYs25CQVaVSbtUiQpFQkqe97PFI',
    appId: '1:66754744895:android:5e9736b7306a1e8949de8a',
    messagingSenderId: '66754744895',
    projectId: 'maligali-5bac7',
    storageBucket: 'maligali-5bac7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUmeyS1JH6pkFFt-aR22E-eqA13mQpgqM',
    appId: '1:66754744895:ios:87ed888d8cefcf7a49de8a',
    messagingSenderId: '66754744895',
    projectId: 'maligali-5bac7',
    storageBucket: 'maligali-5bac7.appspot.com',
    androidClientId: '66754744895-112fupa6eupr3lkvmkdi2klg62chramo.apps.googleusercontent.com',
    iosClientId: '66754744895-9re8455jsr8astphuelhkrtdcmdbb6el.apps.googleusercontent.com',
    iosBundleId: 'com.absai.maligali',
  );
}
